### ISSUE TITLE
Missing sd3d package

### ISSUE THREAD

**Issue by chaudatascience** [oooolga/Ctrl-V#1]
Hi,
Thank you for the great work!

It seems the code is missing "sd3d" package, such as used [here](https://github.com/oooolga/Ctrl-V/blob/8becd292c6e3b85efd0109ccd36ceb01e038b951/src/ctrlv/models/kitti_object_net.py#L1)

Can you provide some guidance on that?
Thank you!
Best,
Chau

**Comment by chaudatascience** [comment]
replacing `sd3d.utils` by `src.ctrlv.utils` seemed to fix the issue!

But I ran into another error:
`ModuleNotFoundError: No module named 'ctrlv.models.unet_spatio_temporal_condition'`

from this [line](https://github.com/oooolga/Ctrl-V/blob/8becd292c6e3b85efd0109ccd36ceb01e038b951/src/ctrlv/models/__init__.py#L4).

Looks like there is no module named `unet_spatio_temporal_condition`

Can you have a look at this?

Thank you!
Chau

**Comment by oooolga** [comment]
@chaudatascience Thank you for your interest in our work and for bringing this to our attention. You are correct that we renamed our project, which caused the issues. Your suggestion to rename `sd3d` to `ctrlv` was spot on.  I have committed to a new update, and I am checking if any naming issues are remaining now. :))

**Comment by chaudatascience** [comment]
Thank you for your quick response!

It seems the new version is still missing `unet_spatio_temporal_condition.py` in `src/ctrlv/models`, which is used [here](https://github.com/oooolga/Ctrl-V/blob/d03442771905acb42935fbe7777c198b9bc6ec78/src/ctrlv/models/__init__.py#L4)

Can you provide the missing file too, thank you!

Best,
Chau

**Comment by oooolga** [comment]
@chaudatascience Thank you so much for spotting this problem. The file was git-ignored, and I would not have realized it was not uploaded without your comment. Please let me know if there is any other issue.
